/// Represents a system alert or message sent to a user.
///
/// This model encapsulates the details of a notification, which is often 
/// generated by background services (like budget monitoring) and broadcasted 
/// via the Observer pattern to keep the user informed of important events.
class NotificationModel {
  /// The unique identifier for the notification.
  int notificationId;
  
  /// The ID of the user intended to receive this notification.
  int userId;
  
  /// The category or classification of the alert (e.g., 'BUDGET_WARNING', 'SYSTEM_UPDATE').
  String type;
  
  /// The main text content of the notification.
  String message;
  
  /// Indicates whether the user has viewed this notification.
  /// 
  /// Defaults to `false` when a new notification is generated.
  bool isRead;
  
  /// The exact date and time the notification was triggered.
  DateTime timestamp;

  /// Creates a new [NotificationModel] instance.
  NotificationModel({
    required this.notificationId,
    required this.userId,
    required this.type,
    required this.message,
    this.isRead = false,
    required this.timestamp,
  });

  /// Converts the [NotificationModel] instance into a Map for database storage.
  ///
  /// Converts the boolean [isRead] flag into an integer (1 or 0) for SQLite 
  /// compatibility, and formats the [timestamp] as an ISO-8601 string.
  Map<String, dynamic> toMap() =>
  {
        'notificationId': notificationId,
        'userId': userId,
        'type': type,
        'message': message,
        'isRead': isRead ? 1 : 0,
        'timestamp': timestamp.toIso8601String(),
  };

  /// Reconstructs a [NotificationModel] instance from a local SQLite database [map].
  factory NotificationModel.fromMap(Map<String, dynamic> map) => NotificationModel(
        notificationId: map['notificationId'],
        userId: map['userId'],
        type: map['type'],
        message: map['message'],
        isRead: map['isRead'] == 1,
        timestamp: DateTime.parse(map['timestamp']),
      );
}
